version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev

    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: